### ISSUE TITLE
RC: Crash on source server

### ISSUE THREAD

**Issue by atomy** [atomy/rustdroid#30]
```
2024-12-28 04:04:51.919 20443-20551 AndroidRuntime          de.mbdesigns.rustdroid               E  FATAL EXCEPTION: RustServerHandler
                                                                                                    Process: de.mbdesigns.rustdroid, PID: 20443
                                                                                                    java.lang.IndexOutOfBoundsException: index=6069 out of bounds (limit=6069)
                                                                                                    	at java.nio.Buffer.checkIndex(Buffer.java:756)
                                                                                                    	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:226)
                                                                                                    	at iogames.regam.service.parser.RustLegacyRconParser.parseTrimmedResponse(RustLegacyRconParser.java:208)
                                                                                                    	at iogames.regam.service.parser.RustLegacyRconParser.parse(RustLegacyRconParser.java:69)
                                                                                                    	at iogames.regam.query.ServerConnection.parseIncommingData(ServerConnection.java:249)
                                                                                                    	at iogames.regam.query.ServerConnection.doReceive(ServerConnection.java:165)
                                                                                                    	at iogames.regam.query.ServerConnection.loop(ServerConnection.java:104)
                                                                                                    	at iogames.regam.ServerHandler.run(ServerHandler.java:177)
```

**Comment by atomy** [comment]
fixed buffer size
